// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.jsx"
import * as $_500 from "./routes/_500.jsx"
import * as $_app from "./routes/_app.tsx"
import * as $_middleware from "./routes/_middleware.js"
import * as $index from "./routes/index.jsx"
import * as $menu from "./routes/menu.jsx"
import * as $order from "./routes/order.jsx"
import * as $sitemap_xml from "./routes/sitemap.xml.js"
import * as $uploads_file_ from "./routes/uploads/[file].js"
import * as $Counter from "./islands/Counter.tsx"
import * as $SingleImagePopup from "./islands/SingleImagePopup.jsx"
import * as $Slideshow from "./islands/Slideshow.tsx"
import * as $ThumbnailGallery from "./islands/ThumbnailGallery.tsx"
import type { Manifest } from "$fresh/server.ts"

const manifest = {
  routes: {
    "./routes/_404.jsx": $_404,
    "./routes/_500.jsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.js": $_middleware,
    "./routes/index.jsx": $index,
    "./routes/menu.jsx": $menu,
    "./routes/order.jsx": $order,
    "./routes/sitemap.xml.js": $sitemap_xml,
    "./routes/uploads/[file].js": $uploads_file_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/SingleImagePopup.jsx": $SingleImagePopup,
    "./islands/Slideshow.tsx": $Slideshow,
    "./islands/ThumbnailGallery.tsx": $ThumbnailGallery,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
